### ISSUE TITLE
metrics.yaml AP @ [IoU=0.50:0.95] value inconsistent with provided documentation

### ISSUE THREAD

**Issue by manisoftwartist** [openvinotoolkit/training_extensions#548]
I am trying to perform evaluation of the face detector models provided n the Wider face dataset. I able to reproduce the AP on Wider face easy, medium and hard subsets with `facedetection-0207`. However, when using facedetection-0204, I get different results compared to values provided in your face detection table
https://github.com/openvinotoolkit/training_extensions/tree/develop/models/object_detection/model_templates/face-detection

**Steps to Reproduce**
1. First, instantiate from template using the instruction in Step4a in the above link
2. Then run the evaluation
`python eval.py    --load-weights ${SNAPSHOT}   --test-ann-files ${TEST_ANN_FILE}    --test-data-roots ${TEST_IMG_ROOT}    --save-metrics-to metrics.yaml`

**metrics.yaml** produced:
```
  1 files:
  2 - name: model.bin
  3   sha256: 56e1a20e0cafec806daea8f8ce5abf2fa0e9013a1a6faa046e19dc62cf3021bc
  4   size: 7269680
  5   source: export/model.bin
  6 metrics:
  7 - display_name: Size
  8   key: size
  9   unit: Mp
 10   value: 1.83
 11 - display_name: Complexity
 12   key: complexity
 13   unit: GFLOPs
 14   value: 2.52
 15 - display_name: AP @ [IoU=0.50:0.95]
 16   key: bbox
 17   unit: '%'
 18   value: 14.2
 19 - display_name: AP for faces > 64x64
 20   key: ap_64x64
 21   unit: '%'
 22   value: -1.0
 23 - display_name: WiderFace Easy
 24   key: widerface_e
 25   unit: '%'
 26   value: 90.441
 27 - display_name: WiderFace Medium
 28   key: widerface_m
 29   unit: '%'
 30   value: 85.44
 31 - display_name: WiderFace Hard
 32   key: widerface_h
 33   unit: '%'
 34   value: 52.087
```

**Environment:**
 - OS: Linux Ubuntu 18.04
 - Framework version: PyTorch
 - Python version: 3.6
 - OpenVINO version: 2021.3.394
 - CUDA/cuDNN version: 10.1
 - GPU model and memory: GeForce GTX 1060 3GB

**Comment by morkovka1337** [comment]
Hi.

I'm investigating this.

**Comment by morkovka1337** [comment]
I've managed to reproduce this. It is strange also that AP for faces > 64x64 is -1. We will look at this more precisely and try to find the root cause.

**Comment by morkovka1337** [comment]
Ok, I've got it. Most likely you've (so am I) set `TEST_IMG_ROOT` and `TEST_ANN_FILE` environment variables to `data/airport` (as it is in the readme.md). This is a small (toy) dataset used to test functionality and show how the data and annotation should look like. It is not meant to be used for model quality evaluation.
So to get values reported in the [table](https://github.com/openvinotoolkit/training_extensions/blob/develop/models/object_detection/model_templates/face-detection/readme.md), instantiate the template and when you are in the template directory (`/tmp/my-face-detection-0204`):
```
export TEST_IMG_ROOT=data/wider_face
export TEST_ANN_FILE=data/wider_face/instances_val.json
```

After that, run the eval script and you should get the desired `metrics.yaml`:
```
files:
- name: snapshot.pth
  sha256: 7a227579f8ebc9017a742ed66b3a9bdc3582090a1c06c9ccbf84722b4a2ffad2
  size: 14904360
  source: snapshot.pth
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.83
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 2.52
- display_name: AP @ [IoU=0.50:0.95]
  key: bbox
  unit: '%'
  value: 21.4
- display_name: AP for faces > 64x64
  key: ap_64x64
  unit: '%'
  value: 92.888
- display_name: WiderFace Easy
  key: widerface_e
  unit: '%'
  value: 90.453
- display_name: WiderFace Medium
  key: widerface_m
  unit: '%'
  value: 85.448
- display_name: WiderFace Hard
  key: widerface_h
  unit: '%'
  value: 52.091
```
Note: I've tested PyTorch model, and for the exported IR model the result should be the same. Let me know if you managed to reproduce the metrics. =)
Good luck!

**Comment by morkovka1337** [comment]
Feel free to reopen this if you don't succeed to reproduce the provided results.

**Comment by morkovka1337** [comment]
Could you, please, share the `metrics.yaml` file like I did above? For now, I have two assumptions why this could be so: either you use different checkpoint or different dataset.

**Comment by manisoftwartist** [comment]
Thanks for reopening the ticket. Sure there are the output metric files
```
files:
- name: snapshot.pth
  sha256: 7a227579f8ebc9017a742ed66b3a9bdc3582090a1c06c9ccbf84722b4a2ffad2
  size: 14904360
  source: snapshot.pth
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.83
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 2.52
- display_name: AP @ [IoU=0.50:0.95]
  key: bbox
  unit: '%'
  value: 21.4
- display_name: AP for faces > 64x64
  key: ap_64x64
  unit: '%'
  value: 92.777
- display_name: WiderFace Easy
  key: widerface_e
  unit: '%'
  value: 90.308
- display_name: WiderFace Medium
  key: widerface_m
  unit: '%'
  value: 85.121
- display_name: WiderFace Hard
  key: widerface_h
  unit: '%'
  value: 51.714
```
And for the converted model
```
files:
- name: model.bin
  sha256: 0c6d6646355352a7dc4ac8a01524b72fa4a82d78d82ad65a46bee7dc3a0952df
  size: 7269712
  source: exports/onnx/2e8b4da409be1fae47cb72e09806a7d8/model.bin
metrics:
- display_name: Size
  key: size
  unit: Mp
  value: 1.83
- display_name: Complexity
  key: complexity
  unit: GFLOPs
  value: 2.52
- display_name: AP @ [IoU=0.50:0.95]
  key: bbox
  unit: '%'
  value: 21.4
- display_name: AP for faces > 64x64
  key: ap_64x64
  unit: '%'
  value: 92.761
- display_name: WiderFace Easy
  key: widerface_e
  unit: '%'
  value: 90.295
- display_name: WiderFace Medium
  key: widerface_m
  unit: '%'
  value: 85.113
- display_name: WiderFace Hard
  key: widerface_h
  unit: '%'
  value: 51.708
```
